# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

assets:
  compress:
    js:  uglifier
    css: sass

exclude:
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor

social:
  - abbr: linkedin
    name: LinkedIn
    url:  http://linkedin.com/pub/cami-thurber/20/195/824
  - abbr: dribbble
    name: Dribbble
    url:  http://dribbble.com/silen6
  - abbr: facebook
    name: Facebook
    url:  http://facebook.com/silen6
  - abbr: twitter
    name: Twitter
    url:  https://twitter.com/silen6design
  - abbr: instagram
    name: Instagram
    url:  https://instagram.com/silen6
  - abbr: envelope
    name: Email
    url:  mailto:cami@silen6.com

analytics:
  google:
    tracking_id: 'UA-46268100-1'
    domain: 'silen6.com'
